---
- name: Install and configure Zabbix with PostgreSQL
  hosts: zabbix
  become: yes

  vars_files:
    - "./zabbix/zabbix_dbpasswd.yml"

  roles:
    - role: psql
    - role: geerlingguy.apache
    - role: geerlingguy.php
    - role: community.zabbix.zabbix_server
      vars:
        zabbix_server_database: pgsql
        zabbix_server_database_long: postgresql
        zabbix_server_dbport: 5432
        zabbix_server_dbpassword: "{{ zabbix_db_password_hash }}"
    - role: community.zabbix.zabbix_web
      vars:
        zabbix_api_server_url: "{{ zabbix_ext_ip }}"
        zabbix_server_database: pgsql
        zabbix_db_type_long: postgresql
        zabbix_server_dbport: 5432
        zabbix_server_dbpassword: "{{ zabbix_db_password_hash }}"
